const technologiesPercent = {
  "javascript-junior": 15,
  "javascript-junior_advanced": 30,
  "javascript-mid": 45,
  "javascript-mid_advanced": 60,
  "javascript-senior": 75,
  "javascript-senior_advanced": 90,
  "javascript-legendary": 100,
  "html-junior": 15,
  "html-junior_advanced": 30,
  "html-mid": 45,
  "html-mid_advanced": 60,
  "html-senior": 75,
  "html-senior_advanced": 90,
  "html-legendary": 100,
  "css-junior": 15,
  "css-junior_advanced": 30,
  "css-mid": 45,
  "css-mid_advanced": 60,
  "css-senior": 75,
  "css-senior_advanced": 90,
  "css-legendary": 100,
  "python-junior": 15,
  "python-junior_advanced": 30,
  "python-mid": 45,
  "python-mid_advanced": 60,
  "python-senior": 75,
  "python-senior_advanced": 90,
  "python-legendary": 100,
};

export default technologiesPercent;
